#!/bin/sh
ver=$(cat version)
case $1 in
  start)
    if [ ! -f cDIS.pid ]; then
      if [ -d modules/__pycache__ ]; then
        rm -rf modules/__pycache__
      fi
      if [ -d __pycache__ ]; then
        rm -rf __pycache__
      fi
      python3 cDIS.py >> /dev/null &
      pid=$!
      echo $pid > cDIS.pid
      echo "chiruclan.de IRC services ($ver) started into background (PID: $pid)"
    else
      pid=$(cat cDIS.pid)
      status="false"
      for data in $(ps | grep $pid); do
        status="true"
      done
      if [ $status = "false" ]; then
        rm -f cDIS.pid
        sh cDIS start
      else
        echo "chiruclan.de IRC services ($ver) is already running"
      fi
    fi
    ;;
  stop)
    if [ -f cDIS.pid ]; then
      pid=$(cat cDIS.pid)
      kill -9 $pid
      rm -f cDIS.pid
      if [ -d modules/__pycache__ ]; then
        rm -rf modules/__pycache__
      fi
      if [ -d __pycache__ ]; then
        rm -rf __pycache__
      fi
      echo "chiruclan.de IRC services ($ver) is stopped (PID: $pid)"
    else
      echo "chiruclan.de IRC services ($ver) is not running"
    fi
    ;;
  restart)
    if [ -f cDIS.pid ]; then
      sh cDIS stop
      sh cDIS start
    else
      sh cDIS start
    fi
    ;;
  debug)
    while [ 1 ]; do
      if [ -d modules/__pycache__ ]; then
        rm -rf modules/__pycache__
      fi
      if [ -d __pycache__ ]; then
        rm -rf __pycache__
      fi
      python3 cDIS.py
      if [ -d modules/__pycache__ ]; then
        rm -rf modules/__pycache__
      fi
      if [ -d __pycache__ ]; then
        rm -rf __pycache__
      fi
    done
    ;;
  update)
    available=$(curl https://raw.github.com/chiruclanDEdev/cDIS/master/version)
    version=$(cat version)
    if [ $available != $version ]; then
      running="false"
      if [ -f cDIS.pid ]; then
        sh cDIS stop
        running="true"
      fi
      git rm __pycache__
      git rm modules/__pycache__
      git pull origin master
      if [ $running = "true" ]; then
        sh cDIS start
      fi
      echo "Done."
    else
      echo "No update available."
    fi
    ;;
  status)
    if [ -f cDIS.pid ]; then
      pid=$(cat cDIS.pid)
      status="chiruclan.de IRC services ($ver) seems to be crashed"
      for data in $(ps | grep $pid); do
        status="chiruclan.de IRC services ($ver) is running"
      done
    else
      status="chiruclan.de IRC services ($ver) is not running"
    fi
    echo $status
    ;;
  *)
    echo "$0 {start|stop|restart|debug|update|status}"
    ;;
esac
  
