#!/bin/sh
ver=$(cat version)
case $1 in
	start)
		if [ ! -f chiruserv.pid ]; then
			rm -f commands/*.pyc
			if [ -f chiruserv.pyc ]; then
				rm -f chiruserv.pyc
			fi
			python chiruserv.py >> /dev/null &
			pid=$!
			echo $pid > chiruserv.pid
			echo "ChiruServ ($ver) started into background (PID: $pid)"
		else
			pid=$(cat chiruserv.pid)
			status="false"
			for data in $(ps | grep $pid); do
				status="true"
			done
			if [ $status = "false" ]; then
				rm -f chiruserv.pid
				sh chiruserv start
			else
				echo "ChiruServ ($ver) is already running"
			fi
		fi
		;;
	stop)
		if [ -f chiruserv.pid ]; then
			pid=$(cat chiruserv.pid)
			kill -9 $pid
			rm -f chiruserv.pid
			rm -f commands/*.pyc
			if [ -f chiruserv.pyc ]; then
				rm -f chiruserv.pyc
			fi
			echo "ChiruServ ($ver) is stopped (PID: $pid)"
		else
			echo "ChiruServ ($ver) is not running"
		fi
		;;
	restart)
		if [ -f chiruserv.pid ]; then
			sh chiruserv stop
			sh chiruserv start
		else
			sh chiruserv start
		fi
		;;
	debug)
		while [ 1 ]; do
			if [ -f chiruserv.pyc ]; then
				rm -f chiruserv.pyc
			fi
			rm -f commands/*.pyc
			python chiruserv.py
			rm -f commands/*.pyc
			if [ -f chiruserv.pyc ]; then
				rm -f chiruserv.pyc
			fi
		done
		;;
	update)
		available=$(curl https://bitucket.org/ChiruclanDE/chiruserv/raw/master/version)
		version=$(cat version)
		if [ $available != $version ]; then
			running="false"
			if [ -f chiruserv.pid ]; then
				sh chiruserv stop
				running="true"
			fi
			git rm commands/*.pyc
			git add config.cfg
			git commit -m 'Save'
			git pull
			if [ $running = "true" ]; then
				sh chiruserv start
			fi
			echo "Done."
		else
			echo "No update available."
		fi
		;;
	status)
		if [ -f chiruserv.pid ]; then
			pid=$(cat chiruserv.pid)
			status="ChiruServ ($ver) seems to be crashed"
			for data in $(ps | grep $pid); do
				status="ChiruServ ($ver) is running"
			done
		else
			status="ChiruServ ($ver) is not running"
		fi
		echo $status
		;;
	*)
		echo "start | stop | restart | debug | update | status"
		;;
esac
	
