SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `banlist` MODIFY COLUMN `channel`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `banlist` MODIFY COLUMN `ban`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `channel`;
ALTER TABLE `banlist` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `chanlist` MODIFY COLUMN `uid`  varchar(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `chanlist` MODIFY COLUMN `channel`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `uid`;
ALTER TABLE `chanlist` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `channelinfo` MODIFY COLUMN `name`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `channelinfo` MODIFY COLUMN `modes`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `name`;
ALTER TABLE `channelinfo` MODIFY COLUMN `flags`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `modes`;
ALTER TABLE `channelinfo` MODIFY COLUMN `topic`  varchar(2048) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `flags`;
ALTER TABLE `channelinfo` MODIFY COLUMN `welcome`  varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `topic`;
ALTER TABLE `channelinfo` MODIFY COLUMN `spamscan`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `welcome`;
ALTER TABLE `channelinfo` MODIFY COLUMN `fantasy`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `spamscan`;
ALTER TABLE `channelinfo` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `channels` MODIFY COLUMN `channel`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `channels` MODIFY COLUMN `user`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `channel`;
ALTER TABLE `channels` MODIFY COLUMN `flag`  enum('n','q','a','o','h','v','b') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `user`;
ALTER TABLE `channels` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `feedback` MODIFY COLUMN `user`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `feedback` MODIFY COLUMN `text`  varchar(2048) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `user`;
ALTER TABLE `feedback` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `gateway` MODIFY COLUMN `uid`  varchar(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `gateway` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `glines` MODIFY COLUMN `mask`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `glines` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `ipchan` MODIFY COLUMN `ip`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `ipchan` MODIFY COLUMN `channel`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `ip`;
ALTER TABLE `ipchan` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `memo` MODIFY COLUMN `user`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `memo` MODIFY COLUMN `source`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `user`;
ALTER TABLE `memo` MODIFY COLUMN `message`  varchar(2048) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `source`;
ALTER TABLE `memo` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `modules` MODIFY COLUMN `name`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `modules` MODIFY COLUMN `class`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `name`;
ALTER TABLE `modules` MODIFY COLUMN `command`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `class`;
ALTER TABLE `modules` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `online` MODIFY COLUMN `uid`  varchar(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `online` MODIFY COLUMN `nick`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `uid`;
ALTER TABLE `online` MODIFY COLUMN `address`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `nick`;
ALTER TABLE `online` MODIFY COLUMN `host`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `address`;
ALTER TABLE `online` MODIFY COLUMN `username`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `host`;
ALTER TABLE `online` ADD COLUMN `account`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `username`;
ALTER TABLE `online` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `opers` MODIFY COLUMN `uid`  varchar(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `opers` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `statistics` MODIFY COLUMN `attribute`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL FIRST ;
ALTER TABLE `statistics` MODIFY COLUMN `value`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `attribute`;
ALTER TABLE `statistics` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `suspended` MODIFY COLUMN `channel`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `suspended` MODIFY COLUMN `reason`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `channel`;
ALTER TABLE `suspended` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `trust` MODIFY COLUMN `address`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `trust` MODIFY COLUMN `limit`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `address`;
ALTER TABLE `trust` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `users` MODIFY COLUMN `name`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `users` MODIFY COLUMN `pass`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `name`;
ALTER TABLE `users` MODIFY COLUMN `email`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `pass`;
ALTER TABLE `users` MODIFY COLUMN `flags`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `email`;
ALTER TABLE `users` MODIFY COLUMN `modes`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `flags`;
ALTER TABLE `users` MODIFY COLUMN `suspended`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `modes`;
ALTER TABLE `users` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
ALTER TABLE `vhosts` MODIFY COLUMN `user`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `vhosts` MODIFY COLUMN `vhost`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `user`;
ALTER TABLE `vhosts` MODIFY COLUMN `active`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `vhost`;
ALTER TABLE `vhosts` DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci;
DROP TABLE `temp_nick`;
SET FOREIGN_KEY_CHECKS=1;