SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `chanlist` MODIFY COLUMN `uid`  varchar(9) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `gateway` MODIFY COLUMN `uid`  varchar(9) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `online` MODIFY COLUMN `uid`  varchar(9) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
ALTER TABLE `opers` MODIFY COLUMN `uid`  varchar(9) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL FIRST ;
SET FOREIGN_KEY_CHECKS=1;