ALTER TABLE `modules` ADD COLUMN `oper` INT(1) NOT NULL DEFAULT 0 AFTER `class`;
ALTER TABLE `modules` ADD COLUMN `auth` INT(1) NOT NULL DEFAULT 0 AFTER `oper`;
ALTER TABLE `modules` ADD COLUMN `help` VARCHAR(255) AFTER `command`;
ALTER TABLE `trust` ADD COLUMN `timestamp` BIGINT(20) NOT NULL;